# Student Loan Risk with Deep Learning

In [1]:
# Imports
import pandas as pd
from pathlib import Path
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `student_loans.csv` file into a Pandas DataFrame. Review the DataFrame, looking for columns that could eventually define your features and target variables.

In [2]:
# Read the csv into a Pandas DataFrame
file_path = "https://static.bc-edx.com/mbc/ai/m6/datasets/student_loans.csv"
loan_df = pd.read_csv(file_path)

# Review the DataFrame
loan_df.head(20)

,payment_history,location_parameter,stem_degree_score,gpa_ranking,alumni_success,study_major_code,time_to_completion,finance_workshop_score,cohort_ranking,total_loan_score,financial_aid_score,credit_ranking
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
5,7.4,0.660,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,9.4,5
6,7.9,0.600,0.06,1.6,0.069,15.0,59.0,0.9964,3.30,0.46,9.4,5
7,7.3,0.650,0.00,1.2,0.065,15.0,21.0,0.9946,3.39,0.47,10.0,7
8,7.8,0.580,0.02,2.0,0.073,9.0,18.0,0.9968,3.36,0.57,9.5,7
9,7.5,0.500,0.36,6.1,0.071,17.0,102.0,0.9978,3.35,0.80,10.5,5
10,6.7,0.580,0.08,1.8,0.097,15.0,65.0,0.9959,3.28,0.54,9.2,5
11,7.5,0.500,0.36,6.1,0.071,17.0,102.0,0.9978,3.35,0.80,10.5,5
12,5.6,0.615,0.00,1.6,0.089,16.0,59.0,0.9943,3.58,0.52,9.9,5
13,7.8,0.610,0.29,1.6,0.114,9.0,29.0,0.9974,3.26,1.56,9.1,5
14,8.9,0.620,0.18,3.8,0.176,52.0,145.0,0.9986,3.16,0.88,9.2,5
15,8.9,0.620,0.19,3.9,0.170,51.0,148.0,0.9986,3.17,0.93,9.2,5
16,8.5,0.280,0.56,1.8,0.092,35.0,103.0,0.9969,3.30,0.75,10.5,7
17,8.1,0.560,0.28,1.7,0.368,16.0,56.0,0.9968,3.11,1.28,9.3,5
18,7.4,0.590,0.08,4.4,0.086,6.0,29.0,0.9974,3.38,0.50,9.0,4
19,7.9,0.320,0.51,1.8,0.341,17.0,56.0,0.9969,3.04,1.08,9.2,6

In [3]:
# Review the data types associated with the columns
loan_df.dtypes

payment_history           float64
location_parameter        float64
stem_degree_score         float64
gpa_ranking               float64
alumni_success            float64
study_major_code          float64
time_to_completion        float64
finance_workshop_score    float64
cohort_ranking            float64
total_loan_score          float64
financial_aid_score       float64
credit_ranking              int64
dtype: object

### Step 2: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “credit_ranking”. The remaining columns should define the features dataset.

In [4]:
# Define the target set y using the credit_ranking column
y = loan_df['credit_ranking'].values

# Display a sample of y
y

array([5, 5, 5, ..., 6, 5, 6], dtype=int64)

In [5]:
# Define features set X by selecting all columns but credit_ranking
X = loan_df.drop(columns='credit_ranking').copy()

# Review the features DataFrame
X

,payment_history,location_parameter,stem_degree_score,gpa_ranking,alumni_success,study_major_code,time_to_completion,finance_workshop_score,cohort_ranking,total_loan_score,financial_aid_score
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4
...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0

In [6]:
loan_df['credit_ranking'].unique()

array([5, 6, 7, 4, 8, 3], dtype=int64)

### Step 3: Split the features and target sets into training and testing datasets.

In [7]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

### Step 4: Use scikit-learn's `StandardScaler` to scale the features data.

In [8]:
# Create a StandardScaler instance
X_scaler = StandardScaler()

# Fit the scaler to the features training dataset
X_scaler.fit(X_train)

# Scale the training and testing data from the features set, X
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

---

## Compile and Evaluate a Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [9]:
# Define the the number of inputs (features) to the model
number_inputs = 11

# Review the number of features
len(X.columns)

11

In [10]:
# Define the number of neurons in the output layer
number_output = 1

In [11]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 = 6

# Review the number hidden nodes in the first layer
hidden_nodes_layer1

6

In [12]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 = 3

# Review the number hidden nodes in the second layer
hidden_nodes_layer2

3

In [13]:
# Create the Sequential model instance
model = Sequential()

In [14]:
# Add the first hidden layer
model.add(Dense(units=hidden_nodes_layer1, input_dim= number_inputs, activation='relu'))

In [15]:
# Add the second hidden layer
model.add(Dense(units=hidden_nodes_layer2, activation='relu'))

In [16]:
# Add the output layer to the model specifying the number of output neurons and activation function
model.add(Dense(units=number_output, activation='linear'))

In [17]:
# Display the Sequential model summary
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 6)                 72

 dense_1 (Dense)             (None, 3)                 21

 dense_2 (Dense)             (None, 1)                 4

=================================================================
Total params: 97 (388.00 Byte)
Trainable params: 97 (388.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

### Step 2: Compile and fit the model using the `mse` loss function, the `adam` optimizer, and the `mse` evaluation metric.

In [18]:
# Compile the Sequential model
model.compile(loss="mean_squared_error", optimizer="adam", metrics=["mse"])

In [19]:
# Fit the model using 50 epochs and the training data
deep_model = model.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
38/38 [==============================] - 0s 1ms/step - loss: 37.2045 - mse: 37.2045
Epoch 2/50
38/38 [==============================] - 0s 812us/step - loss: 34.0893 - mse: 34.0893
Epoch 3/50
38/38 [==============================] - 0s 752us/step - loss: 31.0425 - mse: 31.0425
Epoch 4/50
38/38 [==============================] - 0s 1ms/step - loss: 27.4271 - mse: 27.4271
Epoch 5/50
38/38 [==============================] - 0s 1ms/step - loss: 23.3323 - mse: 23.3323
Epoch 6/50
38/38 [==============================] - 0s 1ms/step - loss: 19.2398 - mse: 19.2398
Epoch 7/50
38/38 [==============================] - 0s 983us/step - loss: 15.4502 - mse: 15.4502
Epoch 8/50
38/38 [==============================] - 0s 1ms/step - loss: 12.1276 - mse: 12.1276
Epoch 9/50
38/38 [==============================] - 0s 1ms/step - loss: 9.3984 - mse: 9.3984
Epoch 10/50
38/38 [==============================] - 0s 1ms/step - loss: 7.2974 - mse: 7.2974
Epoch 11/50
38/38 [==============================] - 0s 925us/step - loss: 5.7620 - mse: 5.7620
Epoch 12/50
38/38 [==============================] - 0s 1ms/step - loss: 4.6885 - mse: 4.6885
Epoch 13/50
38/38 [==============================] - 0s 1ms/step - loss: 3.9371 - mse: 3.9371
Epoch 14/50
38/38 [==============================] - 0s 1ms/step - loss: 3.4137 - mse: 3.4137
Epoch 15/50
38/38 [==============================] - 0s 1ms/step - loss: 3.0458 - mse: 3.0458
Epoch 16/50
38/38 [==============================] - 0s 1ms/step - loss: 2.7729 - mse: 2.7729
Epoch 17/50
38/38 [==============================] - 0s 1ms/step - loss: 2.5643 - mse: 2.5643
Epoch 18/50
38/38 [==============================] - 0s 1ms/step - loss: 2.3963 - mse: 2.3963
Epoch 19/50
38/38 [==============================] - 0s 1ms/step - loss: 2.2557 - mse: 2.2557
Epoch 20/50
38/38 [==============================] - 0s 1ms/step - loss: 2.1391 - mse: 2.1391
Epoch 21/50
38/38 [==============================] - 0s 1ms/step - loss: 2.0304 - mse: 2.0304
Epoch 22/50
38/38 [==============================] - 0s 1ms/step - loss: 1.9336 - mse: 1.9336
Epoch 23/50
38/38 [==============================] - 0s 1ms/step - loss: 1.8406 - mse: 1.8406
Epoch 24/50
38/38 [==============================] - 0s 918us/step - loss: 1.7566 - mse: 1.7566
Epoch 25/50
38/38 [==============================] - 0s 948us/step - loss: 1.6738 - mse: 1.6738
Epoch 26/50
38/38 [==============================] - 0s 1ms/step - loss: 1.5855 - mse: 1.5855
Epoch 27/50
38/38 [==============================] - 0s 1ms/step - loss: 1.4954 - mse: 1.4954
Epoch 28/50
38/38 [==============================] - 0s 1ms/step - loss: 1.4192 - mse: 1.4192
Epoch 29/50
38/38 [==============================] - 0s 810us/step - loss: 1.3403 - mse: 1.3403
Epoch 30/50
38/38 [==============================] - 0s 708us/step - loss: 1.2699 - mse: 1.2699
Epoch 31/50
38/38 [==============================] - 0s 706us/step - loss: 1.2077 - mse: 1.2077
Epoch 32/50
38/38 [==============================] - 0s 846us/step - loss: 1.1558 - mse: 1.1558
Epoch 33/50
38/38 [==============================] - 0s 1ms/step - loss: 1.1121 - mse: 1.1121
Epoch 34/50
38/38 [==============================] - 0s 1ms/step - loss: 1.0716 - mse: 1.0716
Epoch 35/50
38/38 [==============================] - 0s 1ms/step - loss: 1.0365 - mse: 1.0365
Epoch 36/50
38/38 [==============================] - 0s 1ms/step - loss: 1.0037 - mse: 1.0037
Epoch 37/50
38/38 [==============================] - 0s 1ms/step - loss: 0.9724 - mse: 0.9724
Epoch 38/50
38/38 [==============================] - 0s 933us/step - loss: 0.9443 - mse: 0.9443
Epoch 39/50
38/38 [==============================] - 0s 815us/step - loss: 0.9185 - mse: 0.9185
Epoch 40/50
38/38 [==============================] - 0s 761us/step - loss: 0.8938 - mse: 0.8938
Epoch 41/50
38/38 [==============================] - 0s 700us/step - loss: 0.8714 - mse: 0.8714
Epoch 42/50
38/38 [==============================] - 0s 720us/step - loss: 0.8500 - mse: 0.8500
Epoch 43/50
38/38 [==============================] - 0s 786us/step - loss: 0.8306 - mse: 0.8306
Epoch 44/50
38/38 [==============================] - 0s 730us/step - loss: 0.8104 - mse: 0.8104
Epoch 45/50
38/38 [==============================] - 0s 934us/step - loss: 0.7918 - mse: 0.7918
Epoch 46/50
38/38 [==============================] - 0s 943us/step - loss: 0.7755 - mse: 0.7755
Epoch 47/50
38/38 [==============================] - 0s 758us/step - loss: 0.7591 - mse: 0.7591
Epoch 48/50
38/38 [==============================] - 0s 785us/step - loss: 0.7443 - mse: 0.7443
Epoch 49/50
38/38 [==============================] - 0s 888us/step - loss: 0.7291 - mse: 0.7291
Epoch 50/50
38/38 [==============================] - 0s 731us/step - loss: 0.7157 - mse: 0.7157

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [20]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_mse = model.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_mse}")

13/13 - 0s - loss: 0.6888 - mse: 0.6888 - 328ms/epoch - 25ms/step
Loss: 0.6888487935066223, Accuracy: 0.6888487935066223

### Step 4: Save and export your model to an HDF5 file, and name the file `student_loans.h5`.

In [21]:
# Set the model's file path
file_path = Path("saved_models/student_loan_risk.h5")

# Export your model to a HDF5 file
model.save(file_path)

C:\Users\emily.maynard\AppData\Local\anaconda3\envs\dev\lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

---
## Predict Loan Repayment Success by Using your Neural Network Model

### Step 1: Reload your saved model.

In [22]:
# Set the model's file path
file_path = Path("saved_models/student_loan_risk.h5")

# Load the model to a new object
model_imported = tf.keras.models.load_model(file_path)

### Step 2: Make predictions on the testing data.

In [23]:
# Make predictions on the testing data
predictions = model.predict(X_test_scaled).round().astype("int32")

13/13 [==============================] - 0s 2ms/step

### Step 3: Create a DataFrame to compare the predictions with the actual values.

In [24]:
# Create a DataFrame to compare the predictions with the actual values
results = pd.DataFrame({"predictions": predictions.ravel(), "actual": y_test})

### Step 4: Display a sample of the DataFrame you created in step 3.

In [25]:
# Display sample data
results

     predictions  actual
0              4       5
1              4       6
2              5       6
3              6       6
4              7       6
..           ...     ...
395            5       5
396            5       5
397            6       7
398            6       5
399            7       7

[400 rows x 2 columns]